export const mealTypes = ['Breakfast', 'Lunch', 'Dinner', 'Snack', 'Dessert'];
export const difficulties = ['Easy', 'Medium', 'Hard'];

// List of countries with their own cuisine, all European, major Latin American, Asian, and Arab countries, ordered alphabetically
export const countries = [
  // Europe
  'Albania',
  'Andorra',
  'Armenia',
  'Austria',
  'Azerbaijan',
  'Belarus',
  'Belgium',
  'Bosnia and Herzegovina',
  'Bulgaria',
  'Croatia',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Estonia',
  'Finland',
  'France',
  'Georgia',
  'Germany',
  'Greece',
  'Hungary',
  'Iceland',
  'Ireland',
  'Italy',
  'Kazakhstan',
  'Kosovo',
  'Latvia',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Malta',
  'Moldova',
  'Monaco',
  'Montenegro',
  'Netherlands',
  'North Macedonia',
  'Norway',
  'Poland',
  'Portugal',
  'Romania',
  'Russia',
  'San Marino',
  'Serbia',
  'Slovakia',
  'Slovenia',
  'Spain',
  'Sweden',
  'Switzerland',
  'Turkey',
  'Ukraine',
  'United Kingdom',
  // Latin America
  'Argentina',
  'Bolivia',
  'Brazil',
  'Chile',
  'Colombia',
  'Costa Rica',
  'Cuba',
  'Dominican Republic',
  'Ecuador',
  'El Salvador',
  'Guatemala',
  'Honduras',
  'Mexico',
  'Nicaragua',
  'Panama',
  'Paraguay',
  'Peru',
  'Uruguay',
  'Venezuela',
  // Asia
  'Bangladesh',
  'Cambodia',
  'China',
  'India',
  'Indonesia',
  'Japan',
  'Laos',
  'Malaysia',
  'Mongolia',
  'Myanmar',
  'Nepal',
  'Pakistan',
  'Philippines',
  'Singapore',
  'South Korea',
  'Sri Lanka',
  'Taiwan',
  'Thailand',
  'Vietnam',
  // Middle East / Arab World
  'Algeria',
  'Bahrain',
  'Egypt',
  'Iraq',
  'Jordan',
  'Kuwait',
  'Lebanon',
  'Libya',
  'Morocco',
  'Oman',
  'Palestine',
  'Qatar',
  'Saudi Arabia',
  'Sudan',
  'Syria',
  'Tunisia',
  'United Arab Emirates',
  'Yemen',
  // Africa (selected)
  'Ethiopia',
  'Ghana',
  'Kenya',
  'Nigeria',
  'Senegal',
  'South Africa',
  'Tanzania',
  // Oceania
  'Australia',
  'Fiji',
  'New Zealand',
  // North America
  'Canada',
  'United States',
];
