import './globals.css';
import './i18n';
import { Logo } from '@/components/brand/logo';
import { Navigation } from '@/components/navigation/navigation';
import { UserMenu } from '@/components/navigation/user-menu';
import { Toaster } from '@/components/ui/toaster';
import Link from 'next/link';

export const metadata = {
  title: 'Eat Mate - Your source for delicious recipes',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="site-header fixed top-0 flex justify-between items-center px-6 h-16 border-b z-30 bg-background/80 backdrop-blur shadow-sm w-full">
          <Link href="/" aria-label="Home">
            <Logo />
          </Link>
          <div className="flex-1 flex justify-start pl-32">
            <Navigation />
            <div className="ml-auto">
              <UserMenu />
            </div>
          </div>
        </header>
        <main className="pt-16 min-h-[calc(100vh-4rem)]">{children}</main>
        <Toaster />
        <footer className="border-t px-6 py-4 text-center text-sm text-muted-foreground">
          © {new Date().getFullYear()} Eat Mate. All rights reserved.
        </footer>
      </body>
    </html>
  );
}
