export enum Technique {
  Boiling = 'boiling',
  Blanching = 'blanching',
  Steaming = 'steaming',
  Poaching = 'poaching',
  Simmering = 'simmering',
  Stewing = 'stewing',
  Braising = 'braising',
  Roasting = 'roasting',
  Baking = 'baking',
  Grilling = 'grilling',
  Broiling = 'broiling',
  Sauteing = 'sauteing',
  StirFrying = 'stir-frying',
  DeepFrying = 'deep-frying',
  PanFrying = 'pan-frying',
  Smoking = 'smoking',
  Pickling = 'pickling',
  Fermenting = 'fermenting',
  SousVide = 'sous-vide',
  Raw = 'raw',
}
